packageExtensions:
  "@chakra-ui/checkbox@*":
    dependencies:
      framer-motion: "*"
  "@chakra-ui/media-query@*":
    dependencies:
      "@chakra-ui/theme": "*"
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
      react: "*"
  "@chakra-ui/theme-tools@*":
    dependencies:
      "@chakra-ui/system": "*"
  "@chakra-ui/transition@*":
    dependencies:
      framer-motion: "*"
  framer-motion@*:
    dependencies:
      react-dom: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
